### PR TITLE
Add TaxonomyNode model

### PR DESCRIPTION
**Pull request by xavierfav**
I think I am done with adding `TaxonomyNode` and doing some changes needed:
- Add `TaxonomyNode` model
- Adapt methods in `Taxonomy`
- Add `ForeignKey` relation to `TaxonomyNode` in `Annotation`
- Adapt methods `Dataset` model
- Adapt methods for calculating stats in _dataset_templatetags.py_
- Adapt model and view tests
- Adapt create_annotations() in _generate_fake_data.py_
- Migrations: `TaxonomyNode`, FS examples, `Annotation`)

### CODE REVIEW

**Comment by xavierfav** [comment]
Now, I will start:
- Add async task for calculating priority score for `TaxonomyNode`
- Add a field in `TaxonomyNode` model and migration

**Comment by xavierfav** [comment]
Added a task for calculating the number of ground truth annotation for each taxonomy node related to fsd dataset and store it in the `TaxonomyNode` model.

I find it more logic to store the number of ground truth rather than the priority score (see iss #36)

**Comment by xavierfav** [comment]
I just spotted a bug due to changes in `Annotation` model.
The task _compute_dataset_taxonomy_stats_ execute an operation that uses the _value_ field that has been replaced by a `ForeignKey` relation to `TaxonomyNode`

**Comment by xavierfav** [comment]
Starting to work on another issue, I realized that we cannot migrate back on migration 0021.
This migration removes the _value_ field from `Annotation` and there is no way to get back the original data. I guess a reverse migration should be added. Working on it.

**Comment by ffont** [comment]
There are no plans to go back, to me there is no need to write a backwards migration here.

**Comment by xavierfav** [comment]
But now that I am working on the another branch that has not all this changes in the model, I need to be able to go back to an old state of the database.
Or either I can create my new branch from this one...

**Comment by ffont** [comment]
That's true but in this case maybe the best is to wait until this is finished and merged. We could do it today. Otherwise the migration of 700k will take a significant amount of time every time you go backwards and forwards. I don't think it's worth. Just make a new branch from this one if you can't wait until it is merged to master.

**Comment by xavierfav** [comment]
Ok, I see. 
It can wait. 
Did not think about all this problems when starting the new branch...

**Pull request merged**
